# Generated by Django 3.2 on 2021-04-13 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='Fournisseur')),
                ('supplier_address', models.CharField(max_length=100, verbose_name='Adresse fournisseur')),
                ('supplier_mail', models.EmailField(max_length=100, verbose_name='Mail fournisseur')),
                ('supplier_tel', models.IntegerField(verbose_name='Telephone fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100, verbose_name='Nom du produit')),
                ('prod_stock', models.IntegerField(blank=True, verbose_name='Quantité en stock')),
                ('prod_min', models.IntegerField(blank=True, verbose_name='Quantité minimal')),
                ('prod_max', models.IntegerField(blank=True, verbose_name='Quantité maximal')),
                ('prod_ref_in', models.CharField(blank=True, max_length=100, verbose_name='Référence interne')),
                ('prod_ref_out', models.CharField(blank=True, max_length=100, verbose_name='Référence externe')),
                ('prod_date_create', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('prod_date_update', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('prod_img', models.ImageField(blank=True, default='img/product/default_product.png', upload_to='img/product', verbose_name='Image du produit')),
                ('prod_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.supplier')),
            ],
            options={
                'verbose_name': 'Produit',
                'ordering': ['prod_name'],
            },
        ),
    ]
