# Generated by Django 3.2 on 2021-04-13 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210413_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date'], 'verbose_name': 'Commande'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'ligne de commande'},
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 13, 48, 36, 142371)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Adresse fournisseur'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_mail',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Mail fournisseur'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_tel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telephone fournisseur'),
        ),
    ]
