# Generated by Django 3.2 on 2021-04-22 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210421_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 8, 59, 41, 908882)),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_max',
            field=models.PositiveIntegerField(default='1', verbose_name='Quantité maximal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_min',
            field=models.PositiveIntegerField(default='0', verbose_name='Quantité minimal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_name',
            field=models.CharField(max_length=100, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_ref_in',
            field=models.CharField(blank=True, error_messages={'unique': 'La référence interne existe déja'}, max_length=100, unique=True, verbose_name='Référence interne'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_stock',
            field=models.PositiveIntegerField(default='0', verbose_name='Quantité en stock'),
        ),
    ]
