# Generated by Django 3.2 on 2021-04-23 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20210423_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 15, 37, 7, 864000)),
        ),
        migrations.AlterField(
            model_name='resident',
            name='age',
            field=models.CharField(blank=True, max_length=3, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='badge',
            field=models.CharField(blank=True, max_length=100, verbose_name='Badge'),
        ),
    ]
