# Generated by Django 3.2 on 2021-04-24 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 6, 15, 54, 770189)),
        ),
        migrations.AlterField(
            model_name='resident',
            name='age',
            field=models.IntegerField(blank=True, max_length=3, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='birthdate',
            field=models.DateField(blank=True, max_length=100, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='datein',
            field=models.DateField(blank=True, max_length=100, verbose_name="Date d'arrivée"),
        ),
        migrations.AlterField(
            model_name='resident',
            name='room',
            field=models.IntegerField(blank=True, max_length=5, verbose_name='Chambre'),
        ),
    ]
