# Generated by Django 3.2 on 2021-04-24 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20210424_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='datein',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 6, 53, 41, 850723)),
        ),
    ]
