# Generated by Django 3.2 on 2021-05-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20210508_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='age',
            field=models.IntegerField(blank=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='room',
            field=models.IntegerField(blank=True, verbose_name='Chambre'),
        ),
    ]
