# Generated by Django 3.2 on 2021-08-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20210825_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limitfamily',
            old_name='limit_by_week',
            new_name='point_by_week',
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_limit',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('10', '10'), ('15', '15')], default='0', max_length=20, verbose_name='point(s)'),
        ),
    ]
