# Generated by Django 3.2 on 2021-05-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20210510_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fedorder',
            options={'ordering': ['-date'], 'verbose_name': 'Commande - membre du personnel'},
        ),
        migrations.AlterModelOptions(
            name='fedorderitem',
            options={'verbose_name': 'ligne de commande - membre du personnel'},
        ),
        migrations.AddField(
            model_name='basket',
            name='error',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
