# Generated by Django 3.2 on 2021-05-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20210510_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='fedorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=20, verbose_name='Status de la commande'),
        ),
    ]
