# Generated by Django 3.2 on 2021-05-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_fedorder_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fedorder',
            options={'ordering': ['date', 'status'], 'permissions': (('can_close_order', 'Fermer la commande'),), 'verbose_name': 'Commande - membre du personnel'},
        ),
    ]
