# Generated by Django 3.2 on 2021-08-29 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_rename_prd_main_category_product_prod_main_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('error', models.CharField(max_length=200, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('user_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.resident')),
            ],
            options={
                'verbose_name': 'ligne de panier',
            },
        ),
    ]
