# Generated by Django 3.2 on 2021-09-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_auto_20210829_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketresident',
            name='points',
            field=models.IntegerField(default='0', verbose_name='points'),
        ),
    ]
