# Generated by Django 3.2 on 2021-09-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_basketresident_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='fedorderitem',
            name='qty_supplied',
            field=models.PositiveIntegerField(null=True, verbose_name='quantité fournis'),
        ),
    ]
