# Generated by Django 3.2 on 2021-09-03 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0035_fedorder_prepared_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fedorder',
            name='order_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fedorder_order_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
