# Generated by Django 3.2 on 2021-09-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_alter_fedorder_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fedorderitem',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
