# Generated by Django 3.2 on 2021-09-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_fedorder_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='datein',
            field=models.DateTimeField(max_length=100, null=True, verbose_name="Date d'arrivée"),
        ),
    ]
