# Generated by Django 3.2 on 2021-09-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_resident_datein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_ref_in',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence interne'),
        ),
    ]
