# Generated by Django 3.2 on 2021-09-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_alter_product_prod_ref_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_sub_category',
            field=models.CharField(choices=[('BUREAUTIQUE', 'BUREAUTIQUE'), ('MOBILIER', 'MOBILIER'), ('NOUVEAU-NEE', 'NOUVEAU-NEE'), ('MATERIEL DESINFECTANT', 'MATERIEL DESINFECTANT'), ('HYGIENE/NETTOYAGE', 'HYGIENE/NETTOYAGE'), ('AUTRE', 'AUTRE')], default='AUTRE', max_length=50, verbose_name='Catégorie secondaire'),
        ),
    ]
